import greenfoot.*;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * Written task, I have the markdown version for it. If you want to see it, the file name is: WrittenTask.md
 * # 1. Included a detailed description of features. What am I about to watch?
 * You are watching for __something__:
 * > There are four vehicles in the simulation: Ambulance, Mine Cleaner, IFV (nfantry fighting vehicle) and Tank \
 * > Tank and IFV use a separate rotating tower
 *
 * > > The Complex intelligennt gun tower\
 * > > It will shoot unseen scout shell to aim for the enemy (Mine Dropper)\
 * > > If hit friendly side, stop shooting real shell\
 * > > If hit the emeny, shout live shell
 *
 * > Ambulance heals injured pedestrian \
 * > Mine Cleaner stopes to remove mines from the road \
 * > Civilian tries to cross the road safely \
 * > MineDropper acts as an enemy and place mines in road lanes
 * > I implemented advaced lane changing using trigonometry\
 * > The Gun towr rotate towards the target\
 * > After enough Mine Dropper were killed, it will trigger a air strike\
 * > JDAMs will be droppped into the world, destroy all the vehicles.
 *
 * # Description of world and local effect
 * ## World Effect
 * After enough mine droppers were killed, a warning will pop up on the screen "Air Strike Arived"\
 * After 2 seconds, a f15 will fly over the world. \
 * 1 second later, JDAM(Joint Direct Attack Munition)s will hit all the vehicles. Completely destroy them.
 *
 * ## Local Effect
 * A local effect project is explosion. \
 * Explosions are triggered by mines, shells, destroy vehicles and air strikes. \
 * Explosions only affected a limited area for a limited of time. \
 * The explosion also effect nearby pedestrians
 *
 * # Description of Which Vehicles Change Lanes and Under What Conditions
 * Tank, IFV, and Ambulance use the default change lane algorithm and Mine Cleaner uses a special lane change algorithm.\
 * Vehicles try to change lanes when a slow vehicle is ahead of them.\
 * The vehicle change lane with some conditions:
 * > A vehicle only change lane if there is a slower vehilce ahead of them or this is a mine ahead of them (does not work for mine Cleaner)\
 * > Each changing lane will be finsihed in 21 acts\
 * > Each vehicle only change lane if the lane vehicle intends to change has no parallel vehicle
 *
 * # Known BUGS
 * In very complex scene, the FPS could have occasional frame-rate drop.\
 * Two pedestrians may overlap together.\
 * Vehicle may intend to change lane without safe direction from the ahead vehicle. And they crash together. And disappear. \
 * I nearly reach the greenfoot limit, it is better to use unity and C# to code the program.
 *
 * # Credits
 * I use codex to debug my and create certain codes. They are:
 * > Vehicleworld.java to avoid pedestrians spawn on the rock in my background\
 * > Pedestrian.java used for movement checking against Pedestrian's overlap with rocks in background\
 * > Tower.java for improved performance\
 * > ScreenMessage.java created by codex\
 * > JDAM Draw by codex
 * > background
 *
 * By Jordan Cohen:
 * > SuperSmoothMover.java class\
 * > TrailPiece.java Class\
 * > Counter.java class\
 * > Started code template
 *
 * Resources generated by gemini:
 * > Civilian \
 * > Mine Dropper \
 * > LandMine \
 * > Ambulance \
 * > Mine Cleaner \
 * > F15
 *
 * https://free-game-assets.itch.io/free-2d-tank-game-assets
 * > Tank, IFV, Tank Tower, IFV Tower
 *
 * ## Sound Effects:
 * > background.mp3: StarWar: https://www.youtube.com/watch?v=Z8rl7L4-YPM&t=607s \
 * > AirJet sound: https://pixabay.com/sound-effects/film-special-effects-fighter-jet-powerful-low-flyby-sfx-337205/ \
 * > shooting sound: https://pixabay.com/sound-effects/film-special-effects-machine-gun-burst-43670/ \
 * > explosion sound:https://mixkit.co/free-sound-effects/explosion/ \
 * > alarm sound: https://pixabay.com/sound-effects/film-special-effects-beep-warning-6387/ \
 * > pickup sound: created by gemini  \
 * > Drop Mine sound: https://pixabay.com/sound-effects/film-special-effects-hard-object-drop-98768/
 */


public class VehicleWorld extends World {
    private static final int AMBIENT_VOLUME = 8;

    // Set Y Positions for Pedestrians to spawn
    public static final int TOP_SPAWN = 190; // Pedestrians who spawn on top
    public static final int BOTTOM_SPAWN = 705; // Pedestrians who spawn on the bottom
    // Codex change: retry pedestrian spawns until they avoid blocked pixels in the collision mask.
    private static final int MAX_PEDESTRIAN_SPAWN_ATTEMPTS = 12;
    private static final int MAX_PEDESTRIANS = 8;
    private static final int PEDESTRIAN_SPAWN_MARGIN = 20;
    // Color Constants
    public static Color BORDER = new Color(217, 217, 217);
    public static Color YELLOW_LINE = new Color(245, 215, 5);
    public static Color WHITE_STREET = new Color(217, 217, 217);

    public static boolean SHOW_SPAWNERS = false;
    private final GreenfootImage background;
    // Codex change: mask image where opaque pixels represent background decorations pedestrians cannot overlap.
    private final GreenfootImage pedestrianCollisionMask;
    // Instance variables / Objects
    private final boolean twoWayTraffic;
    private final boolean splitAtCenter;
    private final int laneHeight;
    private final int laneCount;
    private final int spaceBetweenLanes;
    private final int[] lanePositionsY;
    private final int topY;
    private final VehicleSpawner[] laneSpawners;

    private static Counter fpsCounter;
    private Counter civilianSavedCounter;
    private Counter civilianKilledCounter;
    private Counter mineDropperKilledCounter;
    private Counter minuteTimer;
    private Counter secondTimer;
    private Counter hourCounter;

    private long lastTime = System.currentTimeMillis();
    private int frames;
    private int lastAirStrikeKillCount;
    private int hours;
    private int minutes;
    private int seconds;
    private int actCountDown;

    private GreenfootSound backgroundSound = new GreenfootSound("background.mp3");
    private GreenfootSound airStrikeAlarm = new GreenfootSound("alarm1.wav");
    private GreenfootSound jetSound = new GreenfootSound("jet.wav");

    /**
     * Constructor for objects of class MyWorld.
     * <p>
     * Note that the constructor for the default world is always called
     * when you click the reset button in the Greenfoot scenario screen -
     * this is is basically the code that runs when the program start.
     * Anything that should be done FIRST should go here.
     *
     */
    public VehicleWorld() {
        // Create a new world with 1024x800 pixels, UNBOUNDED
        super(1024, 800, 1, false);

        // This command (from Greenfoot World API) sets the order in which 
        // objects will be displayed. In this example, Pedestrians will
        // always be on top of everything else, then Vehicles (of all
        // sub class types) and after that, all other classes not listed
        // will be displayed in random order. 
        setPaintOrder(Counter.class, ScreenMessage.class, F15.class, Explosion.class, SuperStatBar.class, Tower.class, TankShell.class, Vehicle.class, Pedestrian.class);

        // set up background -- If you change this, make 100% sure
        // that your chosen image is the same size as the World
        background = new GreenfootImage("background.png");
        pedestrianCollisionMask = new GreenfootImage("background_collision.png");
        setBackground(background);

        // Set critical variables - will affect lane drawing
        laneCount = 4;
        laneHeight = 90;
        spaceBetweenLanes = 8;
        splitAtCenter = true;
        twoWayTraffic = true;

        topY = 232;

        // Init lane spawner objects 
        laneSpawners = new VehicleSpawner[laneCount];

        // Prepare lanes method - draws the lanes
        lanePositionsY = prepareLanes(this, background, laneSpawners, topY, laneHeight, laneCount, spaceBetweenLanes, twoWayTraffic, splitAtCenter);

        laneSpawners[0].setSpeedModifier(0.8);

        // Re-apply after drawing lane graphics onto the background image.
        // In Greenfoot, setBackground(...) copies the current image state.
        setBackground(background);
        prepare();

        // Set counters for mine dropper killed, civilian killed and civilian saved to zero.
        MineDropper.resetMineDropperKilled();
        Civilian.resetCivilianKilledCount();
        Ifv.resetCivilianSaved();

        // Set up the counters
        frames = 0;
        lastAirStrikeKillCount = 0;
        fpsCounter = new Counter("FPS: ");
        addObject(fpsCounter, 125, 75);
        civilianSavedCounter = new Counter("Civilian Saved: ");
        addObject(civilianSavedCounter, 512, 75);
        civilianKilledCounter = new Counter("Civilian Killed: ");
        addObject(civilianKilledCounter, 899, 75);
        mineDropperKilledCounter = new Counter("Mine Dropper killed: ");
        addObject(mineDropperKilledCounter, 899, 120);

        hourCounter = new Counter("Hours: ");
        minuteTimer = new Counter("Minutes: ");
        secondTimer = new Counter("Seconds: ");

        addObject(hourCounter, 512, 105);
        addObject(minuteTimer, 512, 135);
        addObject(secondTimer, 512, 165);

        //Init the counter's elements
        actCountDown = 60;
        minutes = 0;
        seconds = 0;
        hours = 0;

        backgroundSound.setVolume(AMBIENT_VOLUME);

    }

    // FPS counter from my grade 11 project.
    private void countFPS() {
        frames++;
        long currentTime = System.currentTimeMillis();
        if (currentTime - lastTime >= 1000) {
            fpsCounter.setValue(frames);
            frames = 0;
            lastTime = currentTime;
        }
    }

    public static int[] prepareLanes(World world, GreenfootImage target, VehicleSpawner[] spawners, int startY, int heightPerLane, int lanes, int spacing, boolean twoWay, boolean centreSplit, int centreSpacing) {
        if (lanes <= 0) {
            throw new IllegalArgumentException("lanes must be greater than 0");
        }
        if (spawners == null || spawners.length < lanes) {
            throw new IllegalArgumentException("spawners array must be non-null and sized for all lanes");
        }

        // Declare an array to store the y values as I calculate them
        int[] lanePositions = new int[lanes];
        // Pre-calculate half of the lane height, as this will frequently be used for drawing.
        // To help make it clear, the heightOffset is the distance from the centre of the lane (it's y position)
        // to the outer edge of the lane.
        int heightOffset = heightPerLane / 2;
        // draw top border
        target.setColor(BORDER);
        target.fillRect(0, startY, target.getWidth(), spacing);

        // Main Loop to Calculate Positions and draw lanes
        for (int i = 0; i < lanes; i++) {
            // calculate the position for the lane
            lanePositions[i] = startY + spacing + (i * (heightPerLane + spacing)) + heightOffset;

            target.fillRect(0, lanePositions[i] + heightOffset, target.getWidth(), spacing);

            // Place spawners and draw lines depending on whether its 2 way and centre split
            if (twoWay && centreSplit) {
                // first half of the lanes go rightward (no option for left-hand drive, sorry UK students .. ?)
                if (i < lanes / 2) {
                    spawners[i] = new VehicleSpawner(false, heightPerLane, i);
                    world.addObject(spawners[i], target.getWidth(), lanePositions[i]);
                } else { // second half of the lanes go leftward
                    spawners[i] = new VehicleSpawner(true, heightPerLane, i);
                    world.addObject(spawners[i], 0, lanePositions[i]);
                }

                // draw yellow lines if middle
                if (i == lanes / 2) {
                    target.setColor(YELLOW_LINE);
                    target.fillRect(0, lanePositions[i] - heightOffset - spacing, target.getWidth(), spacing);

                } else if (i > 0) { // draw white lines if not first lane
                    for (int j = 0; j < target.getWidth(); j += 120) {
                        target.setColor(WHITE_STREET);
                        target.fillRect(j, lanePositions[i] - heightOffset - spacing, 60, spacing);
                    }
                }

            } else if (twoWay) { // not center split
                if (i % 2 == 0) {
                    spawners[i] = new VehicleSpawner(false, heightPerLane, i);
                    world.addObject(spawners[i], target.getWidth(), lanePositions[i]);
                } else {
                    spawners[i] = new VehicleSpawner(true, heightPerLane, i);
                    world.addObject(spawners[i], 0, lanePositions[i]);
                }

                // draw Grey Border if between two "Streets"
                if (i > 0) { // but not in first position
                    if (i % 2 == 0) {
                        target.setColor(BORDER);
                        target.fillRect(0, lanePositions[i] - heightOffset - spacing, target.getWidth(), spacing);

                    } else { // draw dotted lines
                        for (int j = 0; j < target.getWidth(); j += 120) {
                            target.setColor(YELLOW_LINE);
                            target.fillRect(j, lanePositions[i] - heightOffset - spacing, 60, spacing);
                        }
                    }
                }
            } else { // One way traffic
                spawners[i] = new VehicleSpawner(true, heightPerLane, i);
                world.addObject(spawners[i], 0, lanePositions[i]);
                if (i > 0) {
                    for (int j = 0; j < target.getWidth(); j += 120) {
                        target.setColor(WHITE_STREET);
                        target.fillRect(j, lanePositions[i] - heightOffset - spacing, 60, spacing);
                    }
                }
            }
        }
        // draws bottom border
        target.setColor(BORDER);
        target.fillRect(0, lanePositions[lanes - 1] + heightOffset, target.getWidth(), spacing);

        return lanePositions;
    }

    /**
     * A z-sort method which will sort Actors so that Actors that are
     * displayed "higher" on the screen (lower y values) will show up underneath
     * Actors that are drawn "lower" on the screen (higher y values), creating a
     * better perspective.
     */
    public static void zSort (List<Actor> actorsToSort, World world){
        ArrayList<ActorContent> acList = new ArrayList<ActorContent>();
        // Create a list of ActorContent objects and populate it with all Actors sent to be sorted
        for (Actor a : actorsToSort){
            if (a instanceof Effect
                || a instanceof TankShell
                || a instanceof TrailPiece
                || a instanceof Counter
                || a instanceof ScreenMessage
                || a instanceof SuperStatBar){
                continue;
            }
            acList.add (new ActorContent (a, a.getX(), a.getY()));
        }
        // Sort the Actor, using the ActorContent comparitor (compares by y coordinate)
        Collections.sort(acList);
        // Replace the Actors from the ActorContent list into the World, inserting them one at a time
        // in the desired paint order (in this case lowest y value first, so objects further down the
        // screen will appear in "front" of the ones above them).
        for (ActorContent a : acList){
            Actor actor  = a.getActor();
            // Skip actors that have already been removed by another action this frame.
            if (actor.getWorld() != world){
                continue;
            }
            world.removeObject(actor);
            world.addObject(actor, a.getX(), a.getY());
        }
    }

    /**
     * <p>The prepareLanes method is a static (standalone) method that takes a list of parameters about the desired roadway and then builds it.</p>
     *
     * <p><b>Note:</b> So far, Centre-split is the only option, regardless of what values you send for that parameters.</p>
     *
     * <p>This method does three things:</p>
     * <ul>
     *  <li> Determines the Y coordinate for each lane (each lane is centered vertically around the position)</li>
     *  <li> Draws lanes onto the GreenfootImage target that is passed in at the specified / calculated positions.
     *       (Nothing is returned, it just manipulates the object which affects the original).</li>
     *  <li> Places the VehicleSpawners (passed in via the array parameter spawners) into the World (also passed in via parameters).</li>
     * </ul>
     *
     * <p> After this method is run, there is a visual road as well as the objects needed to spawn Vehicles. Examine the table below for an
     * in-depth description of what the roadway will look like and what each parameter/component represents.</p>
     *
     * <pre>
     *                  <=== Start Y
     *  ||||||||||||||  <=== Top Border
     *  /------------\
     *  |            |
     *  |      Y[0]  |  <=== Lane Position (Y) is the middle of the lane
     *  |            |
     *  \------------/
     *  [##] [##] [##| <== spacing ( where the lane lines or borders are )
     *  /------------\
     *  |            |
     *  |      Y[1]  |
     *  |            |
     *  \------------/
     *  ||||||||||||||  <== Bottom Border
     * </pre>
     *
     * @param world         The World that the VehicleSpawners will be added to
     * @param target        The GreenfootImage that the lanes will be drawn on, usually but not necessarily the background of the World.
     * @param spawners      An array of VehicleSpawner to be added to the World
     * @param startY        The top Y position where lanes (drawing) should start
     * @param heightPerLane The height of the desired lanes
     * @param lanes         The total number of lanes desired
     * @param spacing       The distance, in pixels, between each lane
     * @param twoWay        Should traffic flow both ways? Leave false for a one-way street (Not Yet Implemented)
     * @param centreSplit   Should the whole road be split in the middle? Or lots of parallel two-way streets? Must also be two-way street (twoWay == true) or else NO EFFECT
     *
     */
    public static int[] prepareLanes(World world, GreenfootImage target, VehicleSpawner[] spawners, int startY, int heightPerLane, int lanes, int spacing, boolean twoWay, boolean centreSplit) {
        return prepareLanes(world, target, spawners, startY, heightPerLane, lanes, spacing, twoWay, centreSplit, spacing);
    }

    @Override
    public void act() {
        spawn();
        zSort(getObjects(Actor.class), this);
        countFPS();

        // Update counter for my U-I
        civilianSavedCounter.setValue(Ifv.getCivilianSaved());
        civilianKilledCounter.setValue(Civilian.getCivilianKilledCount());
        mineDropperKilledCounter.setValue(MineDropper.getMineDropperKilled());
        launchAirStrike();
        updateTime();
    }

    // A really basic timer, assume 62 acts per second
    private void updateTime() {
        if (actCountDown > 0) {
            actCountDown--;
            return;
        }
        if (actCountDown == 0) {
            seconds++;
            actCountDown = 62;
            if (seconds == 60) {
                minutes++;
                seconds = 0;
            }
            if (minutes == 60) {
                hours++;
                minutes = 0;
            }
        }
        secondTimer.setValue(seconds);
        minuteTimer.setValue(minutes);
        hourCounter.setValue(hours);
    }

    private void launchAirStrike() {
        int killed = MineDropper.getMineDropperKilled();
        if (killed != 0 && killed % 20 == 0 && killed != lastAirStrikeKillCount) {
            // If more than 20 Mine Dropper are killed by Vehicles, an Airstrike would be launch.
            // Play the alarm sound.
            airStrikeAlarm.setVolume(50);
            airStrikeAlarm.play();

            addObject(new ScreenMessage("Air Strike Arrived", 60), getWidth() / 2, getHeight() / 2);
            addObject(new AirStrike(lanePositionsY[Greenfoot.getRandomNumber(4)], jetSound), 0, 0);

            // Record people killed before air strike launch.
            lastAirStrikeKillCount = killed;
        }
    }

    private void spawn() {
        // Chance to spawn a vehicle
        if (Greenfoot.getRandomNumber(laneCount * 15) == 0) {
            int lane = Greenfoot.getRandomNumber(laneCount);
            if (!laneSpawners[lane].isTouchingVehicle()) {
                int rand = Greenfoot.getRandomNumber(100);
                if (rand < 40) {
                    addObject(new MineCleaner(laneSpawners[lane]), 0, 0);
                } else if (rand < 75) {
                    addObject(new Ambulance(laneSpawners[lane]), 0, 0);
                } else if (rand < 90) {
                    addObject(new Ifv(laneSpawners[lane]), 0, 0);
                } else {
                    addObject(new Tank(laneSpawners[lane]), 0, 0);
                }
            }
        }

        // Chance to spawn a Pedestrian
        if (Greenfoot.getRandomNumber(30) == 0) {
            trySpawnPedestrian();
        }
    }

    /**
     * Codex change: spawn a pedestrian only at positions that do not overlap
     * blocked pixels in the background collision mask.
     */
    private void trySpawnPedestrian() {
        boolean spawnAtTop = Greenfoot.getRandomNumber(2) == 0;
        int ySpawnLocation = spawnAtTop ? TOP_SPAWN : BOTTOM_SPAWN;
        int direction = spawnAtTop ? 1 : -1;

        for (int i = 0; i < MAX_PEDESTRIAN_SPAWN_ATTEMPTS; i++) {
            Pedestrian candidate = createPedestrian(direction);
            GreenfootImage image = candidate.getImage();
            int minX = image.getWidth() / 2 + PEDESTRIAN_SPAWN_MARGIN;
            int maxX = getWidth() - image.getWidth() / 2 - PEDESTRIAN_SPAWN_MARGIN;
            if (maxX <= minX) {
                return;
            }

            int xSpawnLocation = Greenfoot.getRandomNumber(maxX - minX + 1) + minX;
            if (!isPedestrianAreaBlocked(xSpawnLocation, ySpawnLocation, image)) {
                addObject(candidate, xSpawnLocation, ySpawnLocation);
                return;
            }
        }
    }

    // END

    /**
     * Create the next pedestrian instance without coupling world logic to a
     * specific Pedestrian subclass.
     */
    private Pedestrian createPedestrian(int direction) {
        if (Greenfoot.getRandomNumber(10) < 5) {
            return new MineDropper(direction, lanePositionsY);
        }
        return new Civilian(direction);
    }

    /**
     * Codex change: check whether a pedestrian image would overlap any blocked
     * pixels in the background collision mask.
     *
     * @param centerX the actor center x-coordinate to test
     * @param centerY the actor center y-coordinate to test
     * @param image   the actor image used to derive the bounding box
     * @return true if any blocked mask pixel is covered by the actor bounds
     */
    public boolean isPedestrianAreaBlocked(int centerX, int centerY, GreenfootImage image) {
        int halfWidth = image.getWidth() / 2;
        int halfHeight = image.getHeight() / 2;
        int left = centerX - halfWidth;
        int right = centerX + halfWidth;
        int top = centerY - halfHeight;
        int bottom = centerY + halfHeight;
        left = Math.max(0, left);
        right = Math.min(pedestrianCollisionMask.getWidth() - 1, right);
        top = Math.max(0, top);
        bottom = Math.min(pedestrianCollisionMask.getHeight() - 1, bottom);

        if (left > right || top > bottom) {
            return true;
        }

        for (int x = left; x <= right; x++) {
            for (int y = top; y <= bottom; y++) {
                if (pedestrianCollisionMask.getColorAt(x, y).getAlpha() > 0) {
                    return true;
                }
            }
        }
        return false;
    }

    //END

    /**
     * Given a lane number (zero-indexed), return the y position
     * in the centre of the lane. (doesn't factor offset, so
     * watch your offset, i.e. with Bus).
     *
     * @param lane the lane number (zero-indexed)
     * @return int the y position of the lane's center, or -1 if invalid
     */
    public int getLaneY(int lane) {
        if (lane >= 0 && lane < lanePositionsY.length) {
            return lanePositionsY[lane];
        }
        return -1;
    }

    /**
     * Given a y-position, return the lane number (zero-indexed).
     * Note that the y-position must be valid, and you should
     * include the offset in your calculations before calling this method.
     * For example, if a Bus is in a lane at y=100, but is offset by -20,
     * it is actually in the lane located at y=80, so you should send
     * 80 to this method, not 100.
     *
     * @param y - the y position of the lane the Vehicle is in
     * @return int the lane number, zero-indexed
     *
     */
    public int getLane(int y) {
        for (int i = 0; i < lanePositionsY.length; i++) {
            if (y == lanePositionsY[i]) {
                return i;
            }
        }
        return -1;
    }

    /**
     * Prepare the world for the start of the program.
     * That is: create the initial objects and add them to the world.
     */
    private void prepare()
    {
    }

    public void started() {
        backgroundSound.playLoop();
    }

    public void stopped() {
        backgroundSound.stop();
    }
}

/**
 * Container to hold and Actor and an LOCAL position (so the data isn't lost when the Actor is temporarily
 * removed from the World).
 */
class ActorContent implements Comparable<ActorContent> {
    private final Actor actor;
    private int xx, yy;

    public ActorContent(Actor actor, int xx, int yy) {
        this.actor = actor;
        this.xx = xx;
        this.yy = yy;
    }

    public void setLocation(int x, int y) {
        xx = x;
        yy = y;
    }

    public int getX() {
        return xx;
    }

    public int getY() {
        return yy;
    }

    public Actor getActor() {
        return actor;
    }

    @Override
    public String toString() {
        return "Actor: " + actor + " at " + xx + ", " + yy;
    }

    @Override
    public int compareTo(ActorContent a) {
        return Integer.compare(this.getY(), a.getY());
    }

}
